version: "3.8"

networks:
    app-tier:
        driver: bridge

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
            - "3306"
        ports:
            - "3306:3306"    
        networks:
            - app-tier      
        environment:
            MYSQL_DATABASE: nest-mall
            MYSQL_ALLOW_EMPTY_PASSWORD: ok
            MYSQL_ROOT_PASSWORD: 12341234
            MYSQL_USER: root
            MYSQL_PASSWORD: 12341234
            MYSQL_ROOT_HOST: '%'
    backend:
        depends_on:
            - db
        build: .
        command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
        ports:  
            - "3000:3000"
        networks:
            - app-tier